# Generated by Django 4.1.7 on 2023-03-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.CharField(max_length=10)),
                ('matn', models.CharField(max_length=50)),
                ('sana', models.DateField()),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asosiy.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profil')),
            ],
        ),
    ]
